import type { CpdSummary } from "../../modules/cpd/cpd-service.js";
import { EmptyState, fmtDate, fmtNumber, Layout, TIER_LABEL, type NavUser } from "./layout.js";

export function CpdPage(props: { user: NavUser; summary: CpdSummary; year?: string | undefined; currentYear: string }) {
  const { summary, year } = props;
  const q = year ? `?year=${encodeURIComponent(year)}` : "";
  return (
    <Layout title="CPD" user={props.user} active="cpd">
      <div className="page-head">
        <div>
          <h1>Continuing professional development</h1>
          <p className="lede">CPD is recorded automatically when you complete a course that carries CPD.</p>
        </div>
        <div className="actions">
          <a className="button secondary" href={`/cpd/transcript${q}`}>View transcript</a>
          <a className="button secondary" href={`/cpd/transcript.csv${q}`} download>Download CSV</a>
        </div>
      </div>
      {summary.totals.length === 0 ? null : (
        <ul className="stats" aria-label="CPD totals">
          {summary.totals.flatMap((t) => [
            <li key={`${t.unit}-y`} className="stat"><span className="stat-value">{fmtNumber(t.byYear[props.currentYear] ?? 0)}</span><span className="stat-label">{t.unit} in {props.currentYear}</span></li>,
            <li key={`${t.unit}-l`} className="stat"><span className="stat-value">{fmtNumber(t.lifetime)}</span><span className="stat-label">{t.unit} in total</span></li>,
          ])}
        </ul>
      )}
      <form method="get" action="/cpd" className="actions no-print">
        <label>Calendar year
          <select name="year" defaultValue={year ?? ""}>
            <option value="">All years</option>
            {summary.years.map((y) => <option key={y} value={y}>{y}</option>)}
          </select>
        </label>
        <button type="submit" className="button small secondary">Show</button>
      </form>
      <h2>CPD record{year ? ` for ${year}` : ""}</h2>
      {summary.awards.length === 0 ? <EmptyState title="No CPD recorded yet"><p>Complete a course with CPD to see it here.</p></EmptyState> : (
        <div className="table-scroll">
          <table>
            <thead><tr><th scope="col">Course</th><th scope="col">Provided by</th><th scope="col">Completed</th><th scope="col" className="num">CPD</th></tr></thead>
            <tbody>
              {summary.awards.map((a) => (
                <tr key={a.id}><td><strong>{a.courseTitle}</strong><br /><span className="muted small">{TIER_LABEL[a.tier] ?? a.tier}</span></td><td>{a.organisationName}</td><td>{fmtDate(a.awardedAt)}</td><td className="num">{fmtNumber(a.value)} {a.unit}</td></tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Layout>
  );
}

export function TranscriptPage(props: { user: NavUser; name: string; summary: CpdSummary; year?: string | undefined; generatedAt: Date }) {
  const { summary } = props;
  return (
    <Layout title="CPD transcript" user={props.user} active="cpd">
      <p className="breadcrumb no-print"><a href="/cpd">CPD</a> › <span aria-current="page">Transcript</span></p>
      <article className="card" aria-labelledby="t-title">
        <p className="tier">The Corporate Governance Institute</p>
        <h1 id="t-title">CPD transcript</h1>
        <dl className="meta">
          <dt>Learner</dt><dd>{props.name}</dd>
          <dt>Period</dt><dd>{props.year ?? "All years"}</dd>
          <dt>Generated</dt><dd>{fmtDate(props.generatedAt)}</dd>
        </dl>
        {summary.awards.length === 0 ? <p>No CPD recorded for this period.</p> : (
          <table>
            <thead><tr><th scope="col">Course</th><th scope="col">Completed</th><th scope="col" className="num">CPD</th></tr></thead>
            <tbody>{summary.awards.map((a) => <tr key={a.id}><td>{a.courseTitle}</td><td>{fmtDate(a.awardedAt)}</td><td className="num">{fmtNumber(a.value)} {a.unit}</td></tr>)}</tbody>
          </table>
        )}
        <h2>Totals</h2>
        <ul>{summary.totals.map((t) => <li key={t.unit}>{fmtNumber(props.year ? t.byYear[props.year] ?? 0 : t.lifetime)} {t.unit}</li>)}</ul>
        <p className="muted small">Generated by TCGI Learning from completion records. Certificates, where applicable, are issued separately via Accredible.</p>
      </article>
      <p className="no-print"><button type="button" className="button" data-print="">Print or save as PDF</button></p>
    </Layout>
  );
}
